### ISSUE TITLE
[CFL] Workflow with pruning has failed

### ISSUE THREAD

**Issue by ligurio** [ligurio/lua-c-api-tests#109]
```
2024-11-25T12:19:57.7575786Z To https://github.com/ligurio/lua-c-api-corpus
2024-11-25T12:19:57.7575990Z    ae48fa81eedd..c76b77a31c9a  cfl -> cfl
2024-11-25T12:19:57.7576356Z 2024-11-25 12:19:57,098 - root - INFO - Done uploading corpus.
2024-11-25T12:19:57.7576901Z 2024-11-25 12:19:57,098 - root - INFO - Deleting corpus and seed corpus of luaL_traceback_test to save disk.
2024-11-25T12:19:58.2831347Z 2024-11-25 12:19:58,282 - root - INFO - Deleting fuzz target: luaL_traceback_test.
2024-11-25T12:19:58.2860908Z 2024-11-25 12:19:58,285 - root - INFO - Done deleting.
2024-11-25T12:19:58.2862717Z 2024-11-25 12:19:58,285 - root - INFO - Fuzzer luaL_traceback_test finished running without reportable crashes.
2024-11-25T12:19:58.2864606Z 2024-11-25 12:19:58,285 - root - INFO - Downloading corpus for lua_load_test to /github/workspace/cifuzz-corpus/lua_load_test.
2024-11-25T12:19:58.7581450Z Reset branch 'cfl'
2024-11-25T12:19:58.7582254Z Branch 'cfl' set up to track remote branch 'cfl' from 'origin'.
2024-11-25T12:19:58.7583144Z Your branch is up to date with 'origin/cfl'.
2024-11-25T12:19:59.5049932Z HEAD is now at c76b77a31c9a Corpus upload
2024-11-25T12:20:01.1976560Z 2024-11-25 12:20:01,197 - root - INFO - Done downloading corpus. Contains 12601 elements.
2024-11-25T12:31:07.3505452Z Traceback (most recent call last):
2024-11-25T12:31:07.3511018Z   File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers_entrypoint.py", line 97, in <module>
2024-11-25T12:31:07.3512505Z     sys.exit(main())
2024-11-25T12:31:07.3513690Z   File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers_entrypoint.py", line 93, in main
2024-11-25T12:31:07.3514677Z     return run_fuzzers_entrypoint()
2024-11-25T12:31:07.3567817Z   File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers_entrypoint.py", line 63, in run_fuzzers_entrypoint
2024-11-25T12:31:07.3568929Z     result = run_fuzzers.run_fuzzers(config)
2024-11-25T12:31:07.3569978Z   File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers.py", line 316, in run_fuzzers
2024-11-25T12:31:07.3570868Z     if not fuzz_target_runner.run_fuzz_targets():
2024-11-25T12:31:07.3572160Z   File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers.py", line 131, in run_fuzz_targets
2024-11-25T12:31:07.3573061Z     result = self.run_fuzz_target(target)
2024-11-25T12:31:07.3574041Z   File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers.py", line 175, in run_fuzz_target
2024-11-25T12:31:07.3574867Z     result = fuzz_target_obj.prune()
2024-11-25T12:31:07.3575538Z   File "/opt/oss-fuzz/infra/cifuzz/fuzz_target.py", line 154, in prune
2024-11-25T12:31:07.3576111Z     result = engine_impl.minimize_corpus(self.target_path, [],
2024-11-25T12:31:07.3577059Z   File "/usr/local/lib/python3.10/site-packages/clusterfuzz/_internal/bot/fuzzers/libFuzzer/engine.py", line 524, in minimize_corpus
2024-11-25T12:31:07.3577906Z     raise TimeoutError('Merging new testcases timed out.')
2024-11-25T12:31:07.3578345Z TimeoutError: Merging new testcases timed out.
```

Full log: https://productionresultssa8.blob.core.windows.net/actions-results/93f2c7cf-ea8a-4975-91c9-63a9b3a477f3/workflow-job-run-7ab7f9b1-b689-5535-a810-dd47bdd8430c/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-11-25T13%3A08%3A18Z&sig=NiOiKQB65efZcsYYhIkshU3Znc8%2F%2FTQC%2FQlkZPHXNNQ%3D&ske=2024-11-25T23%3A59%3A05Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-11-25T11%3A59%3A05Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-11-04&sp=r&spr=https&sr=b&st=2024-11-25T12%3A58%3A13Z&sv=2024-11-04

**Comment by ligurio** [comment]
Related: https://github.com/google/clusterfuzzlite/issues/89

**Comment by ligurio** [comment]
Duplicate of #184.
