### ISSUE TITLE
Fuzzing build failure

### ISSUE THREAD

**Issue by ligurio** [ligurio/lua-c-api-tests#25]
Issue 58707: lua: Fuzzing build failure

```
Step #22 - "build-check-libfuzzer-address-x86_64": DEDUP_TOKEN: __interceptor_realloc--l_alloc--luaM_malloc_
Step #22 - "build-check-libfuzzer-address-x86_64": Indirect leak of 29 byte(s) in 1 object(s) allocated from:
Step #22 - "build-check-libfuzzer-address-x86_64":     #0 0x52f45c in __interceptor_realloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:85:3
Step #22 - "build-check-libfuzzer-address-x86_64":     #1 0x67d0c1 in l_alloc lauxlib.c
Step #22 - "build-check-libfuzzer-address-x86_64":     #2 0x5dfcdd in luaM_malloc_ (/tmp/not-out/tmpkgddl09f/luaL_addgsub_test+0x5dfcdd)
Step #22 - "build-check-libfuzzer-address-x86_64":     #3 0x5c5a73 in luaC_newobjdt (/tmp/not-out/tmpkgddl09f/luaL_addgsub_test+0x5c5a73)
Step #22 - "build-check-libfuzzer-address-x86_64":     #4 0x5c5cd4 in luaC_newobj (/tmp/not-out/tmpkgddl09f/luaL_addgsub_test+0x5c5cd4)
Step #22 - "build-check-libfuzzer-address-x86_64":     #5 0x608850 in createstrobj lstring.c
Step #22 - "build-check-libfuzzer-address-x86_64":     #6 0x60977b in internshrstr lstring.c
Step #22 - "build-check-libfuzzer-address-x86_64":     #7 0x608594 in luaS_newlstr (/tmp/not-out/tmpkgddl09f/luaL_addgsub_test+0x608594)
Step #22 - "build-check-libfuzzer-address-x86_64":     #8 0x695c96 in luaX_init (/tmp/not-out/tmpkgddl09f/luaL_addgsub_test+0x695c96)
Step #22 - "build-check-libfuzzer-address-x86_64":     #9 0x6052dd in f_luaopen lstate.c
Step #22 - "build-check-libfuzzer-address-x86_64":     #10 0x5aaeac in luaD_rawrunprotected (/tmp/not-out/tmpkgddl09f/luaL_addgsub_test+0x5aaeac)
Step #22 - "build-check-libfuzzer-address-x86_64":     #11 0x604d0c in lua_newstate (/tmp/not-out/tmpkgddl09f/luaL_addgsub_test+0x604d0c)
Step #22 - "build-check-libfuzzer-address-x86_64":     #12 0x67cf62 in luaL_newstate (/tmp/not-out/tmpkgddl09f/luaL_addgsub_test+0x67cf62)
Step #22 - "build-check-libfuzzer-address-x86_64":     #13 0x56c5e3 in LLVMFuzzerTestOneInput /src/testdir/tests/luaL_addgsub_test.cc:25:17
Step #22 - "build-check-libfuzzer-address-x86_64":     #14 0x43dec3 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
Step #22 - "build-check-libfuzzer-address-x86_64":     #15 0x43f274 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::__Fuzzer::vector<fuzzer::SizedFile, std::__Fuzzer::allocator<fuzzer::SizedFile> >&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:804:3
Step #22 - "build-check-libfuzzer-address-x86_64":     #16 0x43f749 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, std::__Fuzzer::allocator<fuzzer::SizedFile> >&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:857:3
Step #22 - "build-check-libfuzzer-address-x86_64":     #17 0x42edaf in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:912:6
Step #22 - "build-check-libfuzzer-address-x86_64":     #18 0x458402 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
Step #22 - "build-check-libfuzzer-address-x86_64":     #19 0x7f973375f082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)
Step #22 - "build-check-libfuzzer-address-x86_64": 
Step #22 - "build-check-libfuzzer-address-x86_64": DEDUP_TOKEN: __interceptor_realloc--l_alloc--luaM_malloc_
Step #22 - "build-check-libfuzzer-address-x86_64": SUMMARY: AddressSanitizer: 14961 byte(s) leaked in 165 allocation(s).
Step #22 - "build-check-libfuzzer-address-x86_64": INFO: to ignore leaks on libFuzzer side use -detect_leaks=0.
Step #22 - "build-check-libfuzzer-address-x86_64": 
Step #22 - "build-check-libfuzzer-address-x86_64": MS: 1 ChangeBit-; base unit: adc83b19e793491b1c6ea0fd8b46cd9f32e592fc
Step #22 - "build-check-libfuzzer-address-x86_64": 0x2a,
Step #22 - "build-check-libfuzzer-address-x86_64": *
Step #22 - "build-check-libfuzzer-address-x86_64": artifact_prefix='./'; Test unit written to ./leak-df58248c414f342c81e056b40bee12d17a08bf61
Step #22 - "build-check-libfuzzer-address-x86_64": Base64: Kg==
Step #22 - "build-check-libfuzzer-address-x86_64": 
Step #22 - "build-check-libfuzzer-address-x86_64": ERROR: 18.181818181818183% of fuzz targets seem to be broken. See the list above for a detailed information.
Step #22 - "build-check-libfuzzer-address-x86_64": ********************************************************************************
Step #22 - "build-check-libfuzzer-address-x86_64": Build checks failed.
Step #22 - "build-check-libfuzzer-address-x86_64": To reproduce, run:
Step #22 - "build-check-libfuzzer-address-x86_64": python infra/helper.py build_image lua
Step #22 - "build-check-libfuzzer-address-x86_64": python infra/helper.py build_fuzzers --sanitizer address --engine libfuzzer --architecture x86_64 lua
Step #22 - "build-check-libfuzzer-address-x86_64": python infra/helper.py check_build --sanitizer address --engine libfuzzer --architecture x86_64 lua
Step #22 - "build-check-libfuzzer-address-x86_64": ********************************************************************************
```

[log-f23c4383-7f63-4455-aa2e-2fa7eda2d8cf.txt](https://github.com/ligurio/lua-c-api-tests/files/11732306/log-f23c4383-7f63-4455-aa2e-2fa7eda2d8cf.txt)

**Comment by ligurio** [comment]
Fixed by:
- https://github.com/google/oss-fuzz/pull/10732
- e0ad95058a65c857ed90a26a5ff56cb39db0738d
