### ISSUE TITLE
`luaL_loadbuffer_proto_test` often fails due to OOM

### ISSUE THREAD

**Issue by ligurio** [ligurio/lua-c-api-tests#85]
```
==85855== ERROR: libFuzzer: out-of-memory (used: 2106Mb; limit: 2048Mb)
   To change the out-of-memory limit use -rss_limit_mb=<N>

Live Heap Allocations: 1832284269 bytes in 4368 chunks; quarantined: 216 bytes in 3 chunks; 32943 other chunks; total chunks: 37314; showing top 95% (at most 8 unique contexts)
1073741824 byte(s) (58%) in 1 allocation(s)
    #0 0x563870d0804c in realloc (/home/sergeyb/sources/lua-c-api-tests/build/luajit/tests/capi/luaL_loadbuffer_proto/luaL_loadbuffer_proto_test+0x1ce04c) (BuildId: 6442122e9e32b5e4298f4307ab6fbf1553060f5f)
    #1 0x563870eb426d in lj_mem_realloc /home/sergeyb/sources/lua-c-api-tests/build/luajit/luajit-v2.1/source/src/lj_gc.c:880:7
    #2 0x563870eb8e34 in buf_grow /home/sergeyb/sources/lua-c-api-tests/build/luajit/luajit-v2.1/source/src/lj_buf.c:34:17
    #3 0x563870eb987e in lj_buf_more2 /home/sergeyb/sources/lua-c-api-tests/build/luajit/luajit-v2.1/source/src/lj_buf.c
    #4 0x563870ec9b50 in lj_buf_more /home/sergeyb/sources/lua-c-api-tests/build/luajit/luajit-v2.1/source/src/./lj_buf.h:109:12
    #5 0x563870ec9b50 in lj_meta_cat /home/sergeyb/sources/lua-c-api-tests/build/luajit/luajit-v2.1/source/src/lj_meta.c:289:7
    #6 0x563870ea7944 in lj_BC_CAT /home/sergeyb/sources/lua-c-api-tests/build/luajit/luajit-v2.1/source/src/lj_vm.S:428

733762868 byte(s) (40%) in 7 allocation(s)
    #0 0x563870d0804c in realloc (/home/sergeyb/sources/lua-c-api-tests/build/luajit/tests/capi/luaL_loadbuffer_proto/luaL_loadbuffer_proto_test+0x1ce04c) (BuildId: 6442122e9e32b5e4298f4307ab6fbf1553060f5f)
    #1 0x563870eb426d in lj_mem_realloc /home/sergeyb/sources/lua-c-api-tests/build/luajit/luajit-v2.1/source/src/lj_gc.c:880:7
    #2 0x563870e02401 in lj_str_alloc /home/sergeyb/sources/lua-c-api-tests/build/luajit/luajit-v2.1/source/src/lj_str.c:287:14
    #3 0x563870e01891 in lj_str_new /home/sergeyb/sources/lua-c-api-tests/build/luajit/luajit-v2.1/source/src/lj_str.c:359:12
    #4 0x563870ec9977 in lj_buf_str /home/sergeyb/sources/lua-c-api-tests/build/luajit/luajit-v2.1/source/src/./lj_buf.h:195:10
    #5 0x563870ec9977 in lj_meta_cat /home/sergeyb/sources/lua-c-api-tests/build/luajit/luajit-v2.1/source/src/lj_meta.c:304:23
    #6 0x563870ea7944 in lj_BC_CAT /home/sergeyb/sources/lua-c-api-tests/build/luajit/luajit-v2.1/source/src/lj_vm.S:428

SUMMARY: libFuzzer: out-of-memory
```

<details>
  <summary>reproducer</summary>

```lua
-------------------------
local DEFAULT_NUMBER = 1

local always_number = function(val)
    return tonumber(val) or DEFAULT_NUMBER
end

local not_nan_and_nil = function(val)
    return (val ~= val or val == nil) and DEFAULT_NUMBER or val
end

local __add = function(v1, v2)
    return always_number(v1) + always_number(v2)
end
local __call = function(self)
    return self
end
local __concat = function(v1, v2)
    return tostring(v1) .. tostring(v2)
end
local __div = function(v1, v2)
    return always_number(v1) / always_number(v2)
end
local __index = function(self, key)
    if type(self) == 'table' then
        return rawget(self, key)
    end
    return always_number(key)
end
local __le = function(v1, v2)
    if type(v1) == 'number' and type(v2) == 'number' then
        return v1 <= v2 -- Numeric comparison.
    elseif type(v1) == 'string' and type(v2) == 'string' then
        return v1 <= v2 -- Lexicographic comparison.
    else
        return always_number(v1) <= always_number(v2)
    end
end
local __len = function(_v)
    return DEFAULT_NUMBER
end
local __lt = function(v1, v2)
    if type(v1) == 'number' and type(v2) == 'number' then
        return v1 < v2 -- Numeric comparison.
    elseif type(v1) == 'string' and type(v2) == 'string' then
        return v1 < v2 -- Lexicographic comparison.
    else
        return always_number(v1) < always_number(v2)
    end
end
local __mod = function(v1, v2)
    return always_number(v1) % always_number(v2)
end
local __mul = function(v1, v2)
    return always_number(v1) * always_number(v2)
end
local __newindex = function(self, key, value)
    if type(self) == 'table' then
        if key ~= key or key == nil then
            key = tostring(key)
        end
        rawset(self, key, value)
    end
end
local __pow = function(v1, v2)
    return always_number(v1) ^ always_number(v2)
end
local __sub = function(v1, v2)
    return always_number(v1) - always_number(v2)
end
local __unm = function(v)
    return - always_number(v)
end

debug.setmetatable('string', {
    __add = __add,
    __call = __call,
    __div = __div,
    __index = __index,
    __mod = __mod,
    __mul = __mul,
    __newindex = __newindex,
    __pow = __pow,
    __sub = __sub,
    __unm = __unm,
})
debug.setmetatable(0, {
    __add = __add,
    __call = __call,
    __concat = __concat,
    __div = __div,
    __index = __index,
    __len = __len,
    __newindex = __newindex,
})
debug.setmetatable(nil, {
    __add = __add,
    __call = __call,
    __concat = __concat,
    __div = __div,
    __index = __index,
    __le = __le,
    __len = __len,
    __lt = __lt,
    __mod = __mod,
    __mul = __mul,
    __newindex = __newindex,
    __pow = __pow,
    __sub = __sub,
    __unm = __unm,
})
debug.setmetatable(function() end, {
    __add = __add,
    __concat = __concat,
    __div = __div,
    __index = __index,
    __le = __le,
    __len = __len,
    __lt = __lt,
    __mod = __mod,
    __mul = __mul,
    __newindex = __newindex,
    __pow = __pow,
    __sub = __sub,
    __unm = __unm,
})
debug.setmetatable(true, {
    __add = __add,
    __call = __call,
    __concat = __concat,
    __div = __div,
    __index = __index,
    __le = __le,
    __len = __len,
    __lt = __lt,
    __mod = __mod,
    __mul = __mul,
    __newindex = __newindex,
    __pow = __pow,
    __sub = __sub,
    __unm = __unm,
})
local table_mt = {
    __add = __add,
    __call = __call,
    __concat = __concat,
    __div = __div,
    __le = __le,
    __len = __len,
    __lt = __lt,
    __mod = __mod,
    __mul = __mul,
    __newindex = __newindex,
    __pow = __pow,
    __sub = __sub,
    __unm = __unm,
}

local only_numbers_cmp = function(v1, v2, cmp_op_str)
    local op_func = {
        ['<'] = function(a1, a2) return a1 < a2 end,
        ['<='] = function(a1, a2) return a1 <= a2 end,
        ['>'] = function(a1, a2) return a1 > a2 end,
        ['>='] = function(a1, a2) return a1 >= a2 end,
    }
    if type(v1) == 'number' and
       type(v2) == 'number' then
        return op_func[cmp_op_str](v1, v2)
    end
    return false
end

---------------------- END OF PREAMBLE ----------------------------

-- REPRO 1: string length overflow
--
--[[
counter_0 = 0
Name0 = 'Name' ;
repeat
if counter_0 > 5 then break end
counter_0 = counter_0 + 1
Name0, ( (setmetatable({ [ not_nan_and_nil('Name') ] = Name0 }, table_mt))()):Name0  (setmetatable({  }, table_mt))()['Name']  = (Name0 .. Name0) .. ('Name' .. Name0) .. Name0, 'Name', 'Name' ;
Name0 = Name0 .. Name0 .. (Name0 .. Name0) .. ('Name' and Name0) .. Name0 .. Name0, true ;
until nil;
]]

-- REPRO 2: not enough memory
--
--[[
counter_0 = 0
Name0 = 'Name' ;
repeat
if counter_0 > 5 then break end
counter_0 = counter_0 + 1
Name0, ( (setmetatable({ [ not_nan_and_nil('Name') ] = Name0 }, table_mt))()):Name0  (setmetatable({  }, table_mt))()['Name']  = (Name0 .. Name0) .. ('Name' .. Name0) .. Name0, 'Name', 'Name' ;
Name0 = Name0 .. Name0 .. (Name0 .. Name0) .. ('Name' and Name0) .. Name0 .. Name0, true ;
until nil;
]]
```
  
</details>

<details>
  <summary>protobuf struct</summary>

```protobuf
chunk {
  stat {
  }
  stat {
    repeatcycle {
      block {
        chunk {
          stat {
            list {
              varlist {
                var {
                }
                vars {
                  indexexpr {
                    prefixexp {
                      functioncall {
                        namedArgs {
                          prefixexp {
                            exp {
                              tableconstructor {
                                fieldlist {
                                  firstField {
                                    exprassign {
                                      key {
                                      }
                                      value {
                                        prefixexp {
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                          name {
                            name: ""
                            num: 0
                          }
                          args {
                          }
                        }
                      }
                    }
                    exp {
                    }
                  }
                }
              }
              explist {
                expressions {
                  binary {
                    leftexp {
                      prefixexp {
                        exp {
                          binary {
                            leftexp {
                              prefixexp {
                              }
                            }
                            binop {
                              concat: 4
                            }
                            rightexp {
                              prefixexp {
                              }
                            }
                          }
                        }
                      }
                    }
                    binop {
                      concat: 4
                    }
                    rightexp {
                      binary {
                        leftexp {
                          prefixexp {
                            exp {
                              binary {
                                leftexp {
                                }
                                binop {
                                  concat: 0
                                }
                                rightexp {
                                  prefixexp {
                                  }
                                }
                              }
                            }
                          }
                        }
                        binop {
                          concat: 4
                        }
                        rightexp {
                          prefixexp {
                          }
                        }
                      }
                    }
                  }
                }
                expressions {
                }
                explast {
                }
              }
            }
          }
          stat {
            list {
              varlist {
                var {
                }
              }
              explist {
                expressions {
                  binary {
                    leftexp {
                      binary {
                        leftexp {
                          prefixexp {
                          }
                        }
                        binop {
                          concat: 4
                        }
                        rightexp {
                          prefixexp {
                          }
                        }
                      }
                    }
                    binop {
                      concat: 0
                    }
                    rightexp {
                      binary {
                        leftexp {
                          binary {
                            leftexp {
                              prefixexp {
                                exp {
                                  binary {
                                    leftexp {
                                      prefixexp {
                                      }
                                    }
                                    binop {
                                      concat: 4
                                    }
                                    rightexp {
                                      prefixexp {
                                      }
                                    }
                                  }
                                }
                              }
                            }
                            binop {
                              concat: 4
                            }
                            rightexp {
                              binary {
                                leftexp {
                                  prefixexp {
                                    exp {
                                      binary {
                                        leftexp {
                                        }
                                        binop {
                                          and: 0
                                        }
                                        rightexp {
                                          prefixexp {
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                                binop {
                                  concat: 4
                                }
                                rightexp {
                                  prefixexp {
                                  }
                                }
                              }
                            }
                          }
                        }
                        binop {
                          concat: 4
                        }
                        rightexp {
                          prefixexp {
                          }
                        }
                      }
                    }
                  }
                }
                explast {
                  true: 5
                }
              }
            }
          }
        }
      }
      condition {
        nil: 0
      }
    }
  }
}
```

</details>

**Comment by ligurio** [comment]
Similar problem in gVisor - https://github.com/google/oss-fuzz/issues/7826

**Comment by ligurio** [comment]
https://github.com/google/oss-fuzz/pull/12049
